backend/core/urls.py
from django.contrib import admin
from django.urls import path, include

# document
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Parham Todo API",
        default_version="v1",
        description="this api is for our useless todo app",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="parham.mehrabi.webdev@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("auth/", include("account.urls", namespace="account")),
    path('weather/', include('weather.urls', namespace='weather')),


    # documentation:
    path(
        "swagger/document.yml",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]

backend/todo/api/urls.py
from .views import TaskViewSet
from rest_framework.routers import DefaultRouter

app_name = "api-1"

router = DefaultRouter()

router.register(basename="tasks", viewset=TaskViewSet, prefix="task")

urlpatterns = [
    # path('task/', TaskViewSet.as_view(),),
]
urlpatterns += router.urls

backend/todo/urls.py
from django.urls import path, include
from .views import (
    TodoListView,
    AddTaskView,
    DeleteTask,
    TaskDetailsView,
    UpdateTask,
    ToggleDone,
)

app_name = "todo"

urlpatterns = [
    path("", TodoListView.as_view(), name="todo-list"),
    path("add/", AddTaskView.as_view(), name="add-task"),
    path("delete/<int:pk>", DeleteTask.as_view(), name="delete"),
    path("details/<int:pk>", TaskDetailsView.as_view(), name="details"),
    path("update/<int:pk>", UpdateTask.as_view(), name="edit"),
    path("toggle/<int:pk>", ToggleDone.as_view(), name="toggle"),
    # API path:
    path("api/v1/", include("todo.api.urls", namespace="api-v1"), name="api-v1"),
]

backend/todo/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

user = get_user_model()
# Create your models here.


class Task(models.Model):
    author = models.ForeignKey(user, on_delete=models.CASCADE, blank=True)

    title = models.CharField(max_length=120, blank=False)
    context = models.TextField(blank=True)
    is_complete = models.BooleanField(default=False)

    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_api_url(self):
        return reverse("todo:api-v1:tasks-detail", kwargs={"pk": self.pk})

backend/todo/forms.py
from django import forms
from .models import Task


class CreateTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        exclude = ("created", "is_complete")


class TaskEditForm(forms.ModelForm):
    class Meta:
        model = Task
        exclude = ("author",)


class DoneToggleForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ("is_complete",)

backend/todo/api/views.py
from rest_framework.viewsets import ModelViewSet
from ..models import Task
from .serializers import TaskSerializer
from .permissions import IsOwnerOrSuperUser, IsVerified
from rest_framework.permissions import IsAuthenticated
from django_filters.rest_framework import DjangoFilterBackend, FilterSet, CharFilter
from rest_framework.filters import SearchFilter, OrderingFilter
from .paginations import TasksPagination


class TaskFilter(FilterSet):
    context = CharFilter(field_name="context", lookup_expr="exact")

    class Meta:
        model = Task
        fields = ["context"]


class TaskViewSet(ModelViewSet):
    model = Task
    serializer_class = TaskSerializer
    permission_classes = [IsOwnerOrSuperUser, IsAuthenticated, IsVerified]
    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    ordering = ["id"]
    filterset_fields = {
        "context": ["in", "exact"],
        "author__email": ["exact", "in"],
        "created": ["lt", "gt"],
    }
    # filterset_class = TaskFilter
    # note:1&2
    search_fields = ["title", "context", "author__email"]
    ordering_fields = ["is_complete", "created"]
    pagination_class = TasksPagination

    def get_queryset(self):
        user = self.request.user
        return Task.objects.filter(author=user)


"""
    #1:
        we should just mention the fields but here with a dictionary we declare how exactly we gonna filter
        for example for created we can specify a limited period of time between lt (lower than) and gt(greater than)


    #2:
        we could use a class and use the class in filterset_class rather the filterset_fields for example:
            class MyFilter(filters.FilterSet):
                min_price = filters.NumberFilter(field_name="price", lookup_expr='gte')
                max_price = filters.NumberFilter(field_name="price", lookup_expr='lte')
                class Meta:
                    model = Product
                    fields = ['category', 'in_stock']


            class ProductList(generics.ListAPIView):
                queryset = Product.objects.all()
                serializer_class = ProductSerializer
                filter_backends = (filters.DjangoFilterBackend,)
                filterset_class = MyFilter
"""

backend/todo/views.py
from django.views.generic import (
    ListView,
    CreateView,
    DeleteView,
    DetailView,
    UpdateView,
)
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Task
from .forms import CreateTaskForm, TaskEditForm, DoneToggleForm
from django.urls import reverse_lazy
from django.shortcuts import redirect


class TodoListView(LoginRequiredMixin, ListView):
    """
    list the authenticated user's tasks and send create from among them
    """

    model = Task
    context_object_name = "tasks"
    template_name = "todo/task_main.html"
    paginate_by = 5

    def get_queryset(self):
        objects = Task.objects.filter(author=self.request.user)
        objects = objects.order_by("-created")
        return objects

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = CreateTaskForm()
        return context


class AddTaskView(LoginRequiredMixin, CreateView):
    """
    create new tasks and return to listview page and redirect get requests
    """

    model = Task
    form_class = CreateTaskForm
    success_url = reverse_lazy("todo:todo-list")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get(self, *args, **kwargs):
        return redirect("todo:todo-list")


class DeleteTask(UserPassesTestMixin, DeleteView):
    """
    handle deleting task, check if the user is either the owner of the task or a superuser
    """

    model = Task
    success_url = reverse_lazy("todo:todo-list")

    def test_func(self):
        task = self.get_object()
        return self.request.user == task.author or self.request.user.is_superuser

    # TODO SECURITY: change error from 403 to 404 to avoid revealing number of objects in the database


class TaskDetailsView(UserPassesTestMixin, DetailView):
    """
    returns task's details
    """

    model = Task

    def test_func(self):
        task = self.get_object()
        return self.request.user == task.author or self.request.user.is_superuser

    # TODO SECURITY: change error from 403 to 404 to avoid revealing number of objects in the database


class UpdateTask(UserPassesTestMixin, UpdateView):
    """
    update the task's details and redirect to task's details
    """

    model = Task
    form_class = TaskEditForm
    template_name = "todo/task_edit.html"
    # success_url = reverse_lazy('todo:todo-list')

    def test_func(self):
        task = self.get_object()
        return self.request.user == task.author or self.request.user.is_superuser

    def get_success_url(self):
        return reverse_lazy("todo:details", kwargs={"pk": self.object.id})


class ToggleDone(UserPassesTestMixin, UpdateView):
    """
    toggle status
    """

    model = Task
    form_class = DoneToggleForm
    template_name = "todo/task_edit.html"
    success_url = reverse_lazy("todo:todo-list")

    def test_func(self):
        task = self.get_object()
        return self.request.user == task.author or self.request.user.is_superuser

backend/templates/todo/task_confirm_delete.html
{% extends 'base.html' %}

{%  block content %}
<div class="p-1 mb-1 w-50 ">
    <form method="post">
        {% csrf_token %}
        <p class="text fw-bold">
            You Are Deleting {{ object }}, Are You Sure?
        </p>
        <button class="btn btn-danger"> DELETE</button>
    </form>
</div>
{% endblock %}

backend/templates/todo/task_detail.html
{% extends 'base.html' %}

{%  block content %}
<h1>
    {{ object.title }}
</h1>
<p class="text fw-bold">
    {{ object.context }}
    
</p>
<h6>
    Done: {{ object.is_complete }}
</h6>
<small>
{{ object.author }}-{{ object.created }}
</small>
<hr>
<div class="btn-group">
    <a class= "btn btn-warning btn-sm" href="{% url 'todo:edit' task.id %}">edit</a>
    <a class= "btn btn-danger btn-sm" href="{% url 'todo:delete' task.id %}">delete</a>
</div>
<a href="{% url 'todo:todo-list' %}" class="btn btn-secondary btn-sm m-2 ">back to tasks</a>
{% endblock %}

backend/templates/todo/task_edit.html
{% extends 'base.html' %}

{%  block content %}
<form action="" method="post">
    {% csrf_token %}
    {% if form.errors %}
    <div class="alert alert-danger">
        {% for key,msg in form.errors.items %}
        {{ msg }}
        {% endfor %}
    </div>
    {% endif %}
    <div>
        <h1>title:
        </h1>
        <small class="text text-danger">
            {{ form.title.errors }}
        </small>
            <h1>
                {{ form.title }}

            </h1>
            </div>
    <div>
        <h6>context:</h6>
        {{ form.context }}
    </div>
    <div class="m-1 p-1">
        <h4>is complete:  {{form.is_complete}}</h4>
    </div>
    <div class="d-flex justify-content-center">
        <button class="btn btn-lg btn-success">Submit</button>
    </div>
</form>
{% endblock %}

backend/templates/todo/task_main.html
{% extends 'base.html' %}

{%  block content %}
<div class="p-1 mb-1 w-50 ">

  <form method="post" action="{% url 'todo:add-task' %}">
    {% csrf_token %}
    <div>
      {{form.title.label}} : {{ form.title }}
      <button class="btn btn-success btn-sm" type="submit"> add</button>
      {{form.error}}
    </div>
  </form>
</div>
  <div class=" table-responsive w-50">
    <table class="table table-hover text-center table-bordered">
      <thead class="thead-dark">
        <tr class="border  table-primary" >
          <th scope="col">#</th>
          <th scope="col">title</th>
          <th scope="col">created date</th>
          <th scope="col">is_complete</th>
          <th scope="col">toggle done</th>
        </tr>
      </thead>
      <tbody>
        {% for task in tasks %}
          <tr class="tr" >
            {% with Pcounter=page_obj.start_index|add:forloop.counter0 %}
            <th scope="row">{{ Pcounter }}</th>
            {% endwith %}
            <td>{{ task.title }}</td>
            <td class="table-info"> 
              <a class= "btn border border-dashed border-black" href="{% url 'todo:details' task.id %}">details</a>
            </td>
            {% if task.is_complete %}
            <td class="table-success">
              <form action="{% url 'todo:toggle' task.id %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="is_complete" checked>
                <button class="btn border border-black w-100" type="submit">Done</button>
              </form>
            </td>
            {% else %}
            <td class="table-danger">
              <form action="{% url 'todo:toggle' task.id %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="is_complete" value="checked">
                <button class="btn border border-black w-100" type="submit">False</button>
              </form>
            </td>
            {% endif%}
            <td> 
              <div class="btn-group">
            <a class= "btn btn-warning btn-sm" href="{% url 'todo:edit' task.id %}">edit</a>
            <form action="{% url 'todo:delete' task.id %}" method="post">
              {% csrf_token %}
              <button class="btn btn-danger btn-sm" type="submit">delete</button>
            </form>
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<div class="page">
  {% if is_paginated %}
  <nav aria-label="Page navigation">
    <ul class="pagination">
      {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number}}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
      </li>
      <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
      {% endif %}
      <li class="page-item"><a class="page-link active" href="#">{{ page_obj.number }}</a></li>
    
      {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number}}" aria-label="Next">
          <span class="sr-only">Next</span>
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
    </ul>
  </nav>
  {% endif %}
</div>
{% endblock %}