backend/account/urls.py
from django.urls import path, include
from .views import TodoLogoutView, TodoRegisterView, TodoLoginView


app_name = "account"

urlpatterns = [
    path("logout/", TodoLogoutView.as_view(), name="logout"),
    path("register/", TodoRegisterView.as_view(), name="register"),
    path("login/", TodoLoginView.as_view(), name="login"),
    path("api/v1/", include("account.api.v1.urls"), name="api-v1"),
]

backend/core/urls.py
from django.contrib import admin
from django.urls import path, include

# document
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Parham Todo API",
        default_version="v1",
        description="this api is for our useless todo app",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="parham.mehrabi.webdev@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls", namespace="todo")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("auth/", include("account.urls", namespace="account")),
    path('weather/', include('weather.urls', namespace='weather')),


    # documentation:
    path(
        "swagger/document.yml",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]

backend/todo/urls.py
from django.urls import path, include
from .views import (
    TodoListView,
    AddTaskView,
    DeleteTask,
    TaskDetailsView,
    UpdateTask,
    ToggleDone,
)

app_name = "todo"

urlpatterns = [
    path("", TodoListView.as_view(), name="todo-list"),
    path("add/", AddTaskView.as_view(), name="add-task"),
    path("delete/<int:pk>", DeleteTask.as_view(), name="delete"),
    path("details/<int:pk>", TaskDetailsView.as_view(), name="details"),
    path("update/<int:pk>", UpdateTask.as_view(), name="edit"),
    path("toggle/<int:pk>", ToggleDone.as_view(), name="toggle"),
    # API path:
    path("api/v1/", include("todo.api.urls", namespace="api-v1"), name="api-v1"),
]

backend/weather/urls.py
from django.urls import path, include
from .views import TestWeatherView
app_name = 'weather'

urlpatterns = [
    path('api/v1/', include('weather.api.v1.urls', namespace='api-v1'), name='api-v1'),
    path('test/', TestWeatherView.as_view(), name='test'),
]

backend/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <title>django-cbv-todo</title>
</head>
<body>
<header>
    <div class="d-flex justify-content-between flex-row-reverse">
        {% url 'weather:test' as weather_test_url %}
        {% url 'todo:todo-list' as home %}
        {% url 'account:logout' as logout %}
        {% url 'account:login' as login %}
        {% url 'account:register' as register %}
        <div>
            {% if user.is_authenticated %}
                <a href="{{ logout }}"
                   class="btn {% if request.path == logout %}active  btn-secondary{% endif %}">logout({{ request.user }})</a>

            {% else %}
                <a href="{{ login }}" class="btn {% if request.path == login %}active  btn-secondary{% endif %}">login</a>
                <a href="{{ register }}"
                   class="btn {% if request.path == register %}active  btn-secondary{% endif %}">register</a>
            {% endif %}
        </div>
        <div class="m-1 p-1">
            <a href="{% url 'schema-swagger-ui' %}" class="btn">api docs(swagger)</a>
            <a href="{% url 'schema-redoc' %}" class="btn">api docs(redoc)</a>
            <a href="{{ weather_test_url }}"
               class="btn {% if request.path == weather_test_url %}active  btn-secondary{% endif %}">weather</a>
            <a href="{{ home }}" class="btn {% if request.path == home %}active  btn-secondary{% endif %}">home</a>
        </div>
    </div>


    <hr>
</header>
<!-- end of header -->
<!-- start of main -->
<main>
    <div class="container d-flex justify-content-center align-items-center flex-column">
        {% block content %}

        {% endblock content %}
    </div>
</main>
<!-- end of main -->
<!-- start of footer -->
<footer>

</footer>
<!-- end of footer -->
</body>
{% block js %}{% endblock js %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
</html>